image: ruby:2.5-alpine

stages:
  - dependencies
  - lint
  - test

install_dependencies:
  stage: dependencies
  before_script:
    - ruby -v
  script:
    - apk add --update --no-cache build-base libxml2-dev libxslt-dev
    - gem install bundler
    - bundle install --path vendor

run_linter:
  stage: lint
  script:
    - apk add --update --no-cache build-base libxml2-dev libxslt-dev
    - bundle install --path vendor
    - bundle exec rubocop

automation_test:
  stage: test
  image: gitlab/dnd
  script: 
    - apk add --update --no-cache build-base libxml2-dev libxslt-dev
    - bundle install --path vendor
    - make build
    - make up
    - bundle exec cucumber 
  after_script:
    - make down